Splash Screen API 적용 및 토큰 갱신 로직 추가
boostcampwm2023/and09-PriceGuard pull request #101
Opened 2023-11-22 01:44 UTC by Taewan-P

**#95 가 먼저 Merge되어야 함**

## 진행 내용

- [x] SDK 31 미만에서는 기존 Splash Screen 및 로직 적용
- [x] SDK 31 이상에서는 Splash Screen API 적용 
- [ ] 토큰 갱신 로직 추가

바꾼이유: 사용자에게 SplashScreenActivity의 View가 그려지기전 빈 화면이 뜨는것을 없앨 수 있음

## 스크린샷 (선택)

2023-11-22 17:47 UTC, Taewan-P commented
또한 지금 앱이 재실행될때마다 토큰을 갱신하게끔 구현이 되어있는데 단기간에 앱을 여러번 재실행하게 되면 서버에 부담이 가게 됩니다.
마지막으로 갱신한 날짜를 트래킹 하고 일정 기간이 지났으면 갱신하게끔 구현하는 방법도 좋을 것 같습니다.

2023-11-23 01:40 UTC, EunhoKang requested changes

2023-11-23 01:40 UTC, EunhoKang commented on android/app/src/main/java/app/priceguard/data/dto/RenewResponse.kt
> +}
RenewResult는 레포지토리에서 뷰모델로 결과를 반환하는데만 쓰이는 타입인것 같은데, 그렇다면 dto 디렉토리보다는 다른 곳으로 분리하는게 좋지 않을까요?

2023-11-23 01:40 UTC, EunhoKang commented on android/app/src/main/java/app/priceguard/di/ProductRepositoryModule.kt
> +        ProductRepositoryImpl(productAPI)
👍 👍 👍

2023-11-23 01:40 UTC, EunhoKang commented on android/app/src/main/java/app/priceguard/ui/splash/SplashScreenViewModel.kt
> +    }
https://github.com/boostcampwm2023/and09-PriceGuard/pull/101/files#r1402442746
이 부분이 실행되는 타이밍이 언제인지 모르겠네요.
해당 로직을 메서드로 분리하고 액티비티에서 호출하도록 하면 타이밍 관리가 쉬울 것 같습니다.

2023-11-23 02:06 UTC, EunhoKang commented on android/app/src/main/java/app/priceguard/data/dto/RenewResponse.kt
> +}
이거 근데 다른 파일도 다 이런식이네요. 늦게 봤습니다. 이거 고치면 다른 파일도 변경되어야 할 것 같네요.
변경해도 되지만 이대로 둬도 괜찮을것 같습니다.

2023-11-23 02:15 UTC, EunhoKang approved these changes

2023-11-23 02:15 UTC, ootr47 approved these changes
LGTM

2023-11-23 02:15 UTC, merged