링크 검사, 가격 설정 화면 에러 처리 추가
boostcampwm2023/and09-PriceGuard pull request #140
Opened 2023-11-27 13:04 UTC by ootr47

Resolves #<이슈번호>

## 진행 내용

- [ ]

## 스크린샷 (선택)

2023-11-27 15:20 UTC, Taewan-P requested changes

2023-11-27 15:20 UTC, Taewan-P commented on android/app/src/main/java/app/priceguard/data/repository/ProductRepositoryImpl.kt
> +                renew(repoFun)
현재 `renew()` 함수를 보면 원래 호출한 함수의 결과가 아닌 renew 의 결과를 반환하고 있습니다.

예를 들어 상품 목록을 호출하는 API가 토큰 만료로 실패했을때,
토큰을 갱신 후 갱신에 성공하면 상품 목록을 호출하는 API를 다시 호출 후 그 결과값을 반환하고,
토큰 갱신에 실패했다면 상품 목록을 호출하는 API의 타입에서 `PERMISSION_DENIED`를 호출해야 합니다.

2023-11-27 15:20 UTC, Taewan-P commented on android/app/src/main/java/app/priceguard/data/repository/ProductRepositoryImpl.kt
> +    ): ProductDeleteState {
여기는 어떻게 다른 API들과 동일한 구조로 통일 할 수 있을지 이야기 해보면 좋을 것 같습니다. @EunhoKang

2023-11-27 23:57 UTC, EunhoKang requested changes
수고하셨습니다!

2023-11-27 23:57 UTC, EunhoKang commented on android/app/src/main/java/app/priceguard/ui/additem/link/RegisterItemLinkFragment.kt
> +                    is RegisterItemLinkViewModel.RegisterLinkEvent.UndefinedError -> TODO()
이 경우에 대해서도 처리가 필요하지 않을까 싶습니다. 간단한 토스트 메세지나 다이얼로그 추가 정도?

2023-11-27 23:57 UTC, EunhoKang commented on android/app/src/main/java/app/priceguard/ui/additem/setprice/SetTargetPriceFragment.kt
> +        MaterialAlertDialogBuilder(requireActivity())
R.style.ThemeOverlay_App_MaterialAlertDialog를 추가해주세요.
파라미터로 추가하면 기본 디자인이 아닌 저희 색 테마에 맞는 디자인으로 바뀝니다.
다른 다이얼로그 선언을 참고하시면 됩니다.

2023-11-27 23:57 UTC, EunhoKang commented on android/app/src/main/java/app/priceguard/data/repository/ProductRepositoryImpl.kt
> +        isRenewed: Boolean
현재 인터페이스와 파라미터 이름이 다릅니다.
이 부분은 가독성이 좋지 않을 뿐더러 Named Argument를 활용할 떄 문제를 발생시킬 수 있습니다.
해당 부분 말고도 다른 함수에 대해서도 인터페이스와 파라미터 이름을 통일해주세요.

2023-11-27 23:57 UTC, EunhoKang commented on android/app/src/main/java/app/priceguard/data/repository/ProductRepositoryImpl.kt
> +    ): ProductDeleteState {
이 부분은 그냥 errorHandle 함수와 renew 함수를 활용해서 처리해도 되지 않을까요?
해당 부분만 함수를 사용하지 않고 처리한 이유를 모르겠습니다.

2023-11-28 04:18 UTC, ootr47 commented on android/app/src/main/java/app/priceguard/data/repository/ProductRepositoryImpl.kt
> +        isRenewed: Boolean
수정했습니다!

2023-11-28 04:22 UTC, ootr47 commented on android/app/src/main/java/app/priceguard/ui/additem/link/RegisterItemLinkFragment.kt
> +                    is RegisterItemLinkViewModel.RegisterLinkEvent.UndefinedError -> TODO()
에러 메시지 표시하도록 수정했습니다!

2023-11-28 04:28 UTC, ootr47 commented on android/app/src/main/java/app/priceguard/ui/additem/setprice/SetTargetPriceFragment.kt
> +        MaterialAlertDialogBuilder(requireActivity())
수정완료했습니다!

2023-11-28 04:31 UTC, ootr47 commented on android/app/src/main/java/app/priceguard/data/repository/ProductRepositoryImpl.kt
> +                renew(repoFun)
로직에 오류가 있었네요 수정 완료했습니다!

2023-11-28 04:33 UTC, ootr47 commented on android/app/src/main/java/app/priceguard/data/dto/ErrorState.kt
수정완료했습니다!

2023-11-28 05:11 UTC, EunhoKang approved these changes
LGTM

2023-11-28 05:21 UTC, EunhoKang commented on android/app/src/main/java/app/priceguard/data/repository/ProductRepositoryImpl.kt
> +    ): ProductDeleteState {
해당 부분 수정 완료했습니다. DeleteProduct를 사용하는 뷰모델과 액티비티의 데이터 활용 방식을 수정했습니다.

2023-11-28 05:21 UTC, ootr47 commented on android/app/src/main/java/app/priceguard/data/repository/ProductRepositoryImpl.kt
> +    ): ProductDeleteState {
delete 로직도 다른 요청과 동일한 구조로 수정하였습니다!

2023-11-28 07:28 UTC, Taewan-P approved these changes
수고 많으셨습니다...!

2023-11-28 07:28 UTC, merged