[알람 설정] 상품 가격이 목표가 이하로 내려가면 알람을 받을 수 있다.
boostcampwm2023/and09-PriceGuard pull request #183
Opened 2023-12-07 07:59 UTC by EunhoKang

- Resolves #21 
- Resolves #26 

## 진행 내용

- [ ] FCM 사용을 위한 초기 설정
- [ ] 알람 권한 부여
- [ ] 백그라운드에서 알람 수신
- [ ] 토글 버튼을 통해 알람 수신 설정 차단 기능, Worker로 최적화

## 스크린샷 (선택)

2023-12-07 11:07 UTC, Taewan-P requested changes
Login, Signup에서 Firebase Token을 업데이트할때
login -> token을 datastore에 저장 -> token을 datastore에서 가져옴 -> 해당 토큰으로 firebase token을 업데이트함

순서로 되어있는데 이를 
login -> (token으로 firebase token을 업데이트함, token을 datastore에 저장)((순서 무관))

으로 해도 되지 않을까요?

read operation이 하나 더 늘어났다는 생각이 듭니다.

2023-12-07 11:07 UTC, Taewan-P commented on android/app/src/main/java/app/priceguard/ui/home/HomeActivity.kt
> +    }
이 부분은 어떻게 할까요? 730시간에 한번 또는 로그인/회원가입 시 갱신하니 필요없을까요?

2023-12-07 11:07 UTC, Taewan-P commented on android/app/src/main/java/app/priceguard/ui/home/list/ProductListViewModel.kt
> +    }
이 함수는 어떤 경우에 사용되나요?

2023-12-07 11:07 UTC, Taewan-P commented on android/app/src/main/java/app/priceguard/ui/home/list/UpdateAlarmWorker.kt
> +            val inputData = Data.Builder().putString(ARGUMENT_KEY, inputData).build()
함수 argument랑 변수 이름이 똑같네요...!

2023-12-07 11:12 UTC, EunhoKang commented
> Login, Signup에서 Firebase Token을 업데이트할때 login -> token을 datastore에 저장 -> token을 datastore에서 가져옴 -> 해당 토큰으로 firebase token을 업데이트함
> 
> 순서로 되어있는데 이를 login -> (token으로 firebase token을 업데이트함, token을 datastore에 저장)((순서 무관))
> 
> 으로 해도 되지 않을까요?
> 
> read operation이 하나 더 늘어났다는 생각이 듭니다.

그렇게 했을 경우 Log를 찍었을 때 계속 파라미터로 받는 accessToken이 null이 되어서 순서를 명시했습니다.

2023-12-07 11:26 UTC, EunhoKang commented on android/app/src/main/java/app/priceguard/ui/PriceGuardApp.kt
> +
위 두 개의 코멘트에 담긴 코드는 Worker를 Hilt로 처리하기 위해 사용되었습니다.
해당 코드는 Application 클래스가 Configuration.Provider 인터페이스를 구현하도록 하고 HiltWorkFactory 인스턴스를 삽입하여 WorkManager 에 전달하는 역할을 하며,
상단 코멘트의 xml은 커스텀 Factory를 Worker에 제공하기 위해 기본 제공자를 비활성화하는 역할을 합니다.

참고한 자료는 다음과 같습니다.
https://developer.android.com/training/dependency-injection/hilt-jetpack?hl=ko#workmanager
https://hanyeop.tistory.com/453

2023-12-07 11:27 UTC, ootr47 requested changes
고생하셨습니다!!

2023-12-07 11:33 UTC, EunhoKang commented on android/app/src/main/java/app/priceguard/ui/home/HomeActivity.kt
> +    }
이 부분은 로깅하는 용도로만 썼었네요. 지워서 커밋하겠습니다.

2023-12-07 11:37 UTC, EunhoKang commented on android/app/src/main/java/app/priceguard/ui/home/list/ProductListViewModel.kt
> +    }
아, 이것도 Worker 생성과 함께 더이상 사용되지 않는 함수입니다.
죄송스럽게도 지우는 걸 깜박했네요. 지워서 올려드리겠습니다.

2023-12-07 11:38 UTC, EunhoKang commented on android/app/src/main/java/app/priceguard/ui/home/list/UpdateAlarmWorker.kt
> +            val inputData = Data.Builder().putString(ARGUMENT_KEY, inputData).build()
변경하였습니다. 감사합니다.

2023-12-07 11:44 UTC, EunhoKang commented on android/app/src/main/java/app/priceguard/data/repository/product/ProductRepositoryImpl.kt
> +                            dto.isAlert ?: false,
맞는 말씀인 것 같네요. 수정하겠습니다.

2023-12-07 11:46 UTC, EunhoKang commented on android/app/src/main/java/app/priceguard/data/repository/token/TokenRepositoryImpl.kt
> +            Log.e("ERROR", e.toString())
변경하였습니다.

2023-12-07 11:48 UTC, EunhoKang commented on android/app/src/main/java/app/priceguard/ui/home/HomeActivity.kt
> +    }
위에서 같은 요청이 와서 제거했습니다.

2023-12-07 14:57 UTC, EunhoKang commented
> 현재 푸시알림을 누르면 오류가 뜨고, 확인 버튼을 누르면 SplashActivity로 돌아간 상태에서 유지되는 문제가 있습니다.
> 
> <img alt="image" width="499" src="https://private-user-images.githubusercontent.com/27392567/288762198-da976ca9-b8b4-4840-ab1a-6e63c4a784fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5NTc4NDYsIm5iZiI6MTcwMTk1NzU0NiwicGF0aCI6Ii8yNzM5MjU2Ny8yODg3NjIxOTgtZGE5NzZjYTktYjhiNC00ODQwLWFiMWEtNmU2M2M0YTc4NGZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDEzNTkwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzYzIwMWY5NTJkZjZkMTQ3M2JkZjNjNTg2ZWU4YzhiMWZmNzgyMGE5YzdhNDg4MmFmMmY1MzI0MDBlZGMxOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U6IqgcnOWZP_3mgc4Vlf9sW_qlu5yiHCfwH8zccI5bU">

확인 결과, DB에 없는 데이터 링크일경우 오류가 발생합니다.
이 경우는 실제 사용자 유스케이스에서 발생하지 않는 경우이며, 괜찮을 것 같습니다.

2023-12-07 14:58 UTC, EunhoKang commented
> 1. 알람 스위치를 변경하고 스크롤을 내렸다가 올렸을 때 변경 전 상태로 돌아가는 문제가 있습니다.
>    https://github.com/boostcampwm2023/and09-PriceGuard/assets/83055885/5eb4a460-c933-44fc-bf29-1d6b784ab9f0
> 2. 스위치 변경 후 프래그먼트 전환했다가 돌아왔을 때 깜빡이는 문제가 있습니다
>    https://github.com/boostcampwm2023/and09-PriceGuard/assets/83055885/1bf2c820-0ea0-40d8-bd6c-851a36dc201a

2번은 해결되었습니다. @Taewan-P 님의 코드를 개량하여 토글 버튼 클릭 시마다 뷰모델에 변화를 전달하는 식으로 변경하였습니다.

2023-12-08 01:09 UTC, ootr47 approved these changes

2023-12-08 01:15 UTC, Taewan-P approved these changes

2023-12-08 01:15 UTC, merged