회원탈퇴 기능 추가
boostcampwm2023/and09-PriceGuard pull request #239
Opened 2023-12-28 07:41 UTC by ootr47

- Resolves #170 

## 진행 내용
- [x] 회원 탈퇴 ui 추가
- [ ] 회원 탈퇴 api 연동 

## 스크린샷 (선택)

2024-01-15 12:42 UTC, Taewan-P requested changes
수고하셨습니다!
다만, UI적으로 탈퇴 요청이 이루어지는 동안 네트워크 요청이 처리되고 있다는게 사용자한테 보여지면 좋겠습니다.

2024-01-15 12:42 UTC, Taewan-P commented on android/app/src/main/java/app/priceguard/ui/home/mypage/MyPageSettingAdapter.kt
> +                    binding.root.context.theme.resolveAttribute(R.attr.colorError, typedValue, true)
binding scope 내부에 있는 코드라 binding을 다시 사용할 필요는 없어 보입니다.

```suggestion
                    this.root.context.theme.resolveAttribute(R.attr.colorError, typedValue, true)
```

2024-01-15 12:42 UTC, Taewan-P commented on android/app/src/main/java/app/priceguard/ui/util/ConfirmDialogFragment.kt
> +        return arguments?.getInt("requestCode") ?: 0
Enum의 ordinal에서 0이 나올 가능성도 있지 않나요? 추후에 ConfirmDialog를 재사용하면서 Request Code의 혼선이 생길수도 있을 것 같습니다.

2024-01-15 12:42 UTC, Taewan-P commented on android/app/src/main/java/app/priceguard/ui/home/mypage/DeleteAccountViewModel.kt
> +    fun deleteAccount() {
여러번 연타할 시 연타한 횟수만큼 계속 요청되지 않게끔 조치가 필요해 보입니다.

2024-01-22 08:52 UTC, ootr47 commented on android/app/src/main/java/app/priceguard/ui/util/ConfirmDialogFragment.kt
> +        return arguments?.getInt("requestCode") ?: 0
아 저 코드는 사용되지 않는 코드인데 미처 삭제하지 못한 것 같습니다. 필요없는 함수라 관련 코드들 제거했습니다

2024-01-22 08:53 UTC, ootr47 commented on android/app/src/main/java/app/priceguard/ui/home/mypage/MyPageSettingAdapter.kt
> +                    binding.root.context.theme.resolveAttribute(R.attr.colorError, typedValue, true)
그러네요.. 제거했습니다!

2024-01-25 00:44 UTC, EunhoKang approved these changes
큰 문제점은 안보이네요. 고생많으셨습니다.

2024-01-25 07:50 UTC, Taewan-P approved these changes
수고하셨습니다!
ThrottleClick이 View를 확장했는데 ImageViewAdapter 처럼 BindingAdatper로 사용해도 좋을것 같습니다.

2024-01-25 11:42 UTC, merged