RoundSlider 커스텀 뷰 추가
boostcampwm2023/and09-PriceGuard pull request #240
Opened 2024-01-05 09:34 UTC by ootr47

## 진행 내용

- [x] 슬라이더 ui 구현
- [x] 슬라이드 체인지 리스너 추가
- [x] 슬라이더 속성 변경 함수 제공 (strokeWidth, pointRange, value, maxPercentValue
- [ ] +, - 버튼 클릭으로 value 조정
- [ ] 슬라이더 색상 지정

## 스크린샷 (선택)

- 추가 예정

2024-01-25 01:33 UTC, EunhoKang requested changes
변경사항이 정말 많네요. 고생 많으셨습니다.
아, 그리고 이건 그냥 질문인데 SliderValueChangeListener.kt에서
typealias를 쓰셨던데 function type을 그대로 쓰는 것에 비해 어떤 장점이 있나요?

2024-01-25 01:33 UTC, EunhoKang commented on android/app/src/main/java/app/priceguard/ui/additem/setprice/SetTargetPriceFragment.kt
> +            }
```suggestion
            val sliderValue = (rsTargetPrice.sliderValue - STEP_SIZE).coerceIn(0, MAX_PERCENT)
```

위와 비슷한 방식으로 한줄로 줄일 수 있을 것 같습니다.

2024-01-25 01:33 UTC, EunhoKang commented on android/app/src/main/java/app/priceguard/ui/additem/setprice/SetTargetPriceFragment.kt
> +            }
```suggestion
            val sliderValue = (rsTargetPrice.sliderValue + STEP_SIZE).coerceIn(0, MAX_PERCENT)
```

2024-01-25 01:33 UTC, EunhoKang commented on android/app/src/main/java/app/priceguard/ui/additem/setprice/SetTargetPriceFragment.kt
> +                }
```suggestion
                binding.rsTargetPrice.setSliderMode(if (state.targetPrice > state.productPrice) RoundSliderState.ERROR else RoundSliderState.ACTIVE)
```

한 줄로 줄일수 있을 것 같습니다.

2024-01-25 08:10 UTC, ootr47 commented on android/app/src/main/java/app/priceguard/ui/additem/setprice/SetTargetPriceDialogFragment.kt
> +        return num
coerceIn 적용시키는게 훨씬 읽기 좋네요! 수정했습니다!

2024-01-25 08:16 UTC, ootr47 commented on android/app/src/main/java/app/priceguard/ui/additem/setprice/SetTargetPriceFragment.kt
> +                }
이 부분은 수정하면 한 줄에 코드가 너무 길어지는 것 같아서 일단 유지했습니다

2024-01-25 08:24 UTC, ootr47 commented
> 아, 그리고 이건 그냥 질문인데 SliderValueChangeListener.kt에서
typealias를 쓰셨던데 function type을 그대로 쓰는 것에 비해 어떤 장점이 있나요? 

typealias는 샘플 코드 참고한 것인데 단순히 타입 그대로 지정했을 때 보다 typealias로 이름을 지정한 것이 코드를 이해하기 쉽다고 느껴져서 사용해봤습니다.

2024-01-25 12:35 UTC, Taewan-P requested changes
수고하셨습니다!

2024-01-25 12:35 UTC, Taewan-P commented on android/app/src/main/java/app/priceguard/ui/slider/SliderValueChangeListener.kt
typealias는 누구나 접근 가능한 상태로 정의되어있는데 Slider에 한정된 alias이니 모듈 내에서 사용하게끔 internal을 붙이는게 어떨까요?

2024-01-25 12:35 UTC, Taewan-P commented on android/app/src/main/java/app/priceguard/ui/slider/RoundSlider.kt
함수 순서 맞춰 주세요...! (override, public, private)

2024-01-27 07:19 UTC, ootr47 commented on android/app/src/main/java/app/priceguard/ui/additem/setprice/SetTargetPriceDialogFragment.kt
> +        binding.lifecycleOwner = this
그러네요 수정하겠습니다!

2024-01-27 12:32 UTC, Taewan-P approved these changes
수고하셨습니다!

2024-01-27 13:05 UTC, Taewan-P approved these changes

2024-01-27 22:44 UTC, EunhoKang approved these changes
수고많으셨습니다!

2024-01-27 22:44 UTC, merged