비밀번호 찾기 기능 구현
boostcampwm2023/and09-PriceGuard pull request #256
Opened 2024-02-25 09:35 UTC by ootr47

Resolves #<이슈번호>

## 진행 내용

- [x] 비밀번호 찾기 화면(이메일 인증, 비밀번호 재설정) UI 구현
- [ ] 이메일 인증, 비밀번호 재설정 api 연동

## 스크린샷 (선택)

<img src="https://github.com/boostcampwm2023/and09-PriceGuard/assets/83055885/5b12a09b-1d9a-47fb-b1af-438ac133bb01" width="200px;" alt=""/>

<img src="https://github.com/boostcampwm2023/and09-PriceGuard/assets/83055885/e3837783-09aa-4c46-9fe8-bfe552ff850c" width="200px;" alt=""/>

2024-02-29 16:46 UTC, Taewan-P requested changes
수고하셨습니다!

2024-02-29 16:46 UTC, Taewan-P commented on android/app/src/main/res/layout/fragment_email_verificatioin.xml
파일 이름에 오타가 났네요 😅

2024-02-29 16:46 UTC, Taewan-P commented on android/app/src/main/res/layout/fragment_email_verificatioin.xml
> +            <TextView
상단에 무조건 96dp로 레이아웃을 주기 보다는 CollapsedToolbarLayout을 통해서 가로모드일때는 접혀 불필요한 스크롤을 최대한 줄일 수 있도록 하는것이 좋아 보입니다.

2024-02-29 16:46 UTC, Taewan-P commented on android/app/src/main/java/app/priceguard/ui/util/ImageViewAdapter.kt
파일 이름이 ImageViewAdapter인데 TextInputLayout에 관련된 Binding Adapter 가 추가됐으니 
- Binding Adapter 끼리 모아두는 파일명
- 파일 분리
중 하나로 변경하면 좋을 것 같습니다.

2024-02-29 16:46 UTC, Taewan-P commented on android/app/src/main/java/app/priceguard/ui/login/findpassword/EmailVerificationFragment.kt
> +                emailVerificationViewModel.updateTimer("0")
끝날때도 타이머 시간 형식을 맞추면 좋을 것 같습니다.

또한 타이머가 종료되면 이메일을 받지 못했을 경우를 고려해서 버튼과 텍스트를 재전송 UI로 변경하는게 어떨까요?

2024-03-01 01:54 UTC, EunhoKang requested changes
수고많으셨습니다! 위에서 대부분 말씀해주셔서 드릴 말씀이 없네요.

2024-03-01 01:54 UTC, EunhoKang commented on android/app/src/main/java/app/priceguard/data/repository/token/TokenRepositoryImpl.kt
> +        Log.d("TokenRepoErrorCode", code.toString())
특별한 이유가 없다면 머지 전에 삭제하는게 좋을 것 같습니다.

2024-03-02 06:05 UTC, ootr47 commented on android/app/src/main/res/layout/fragment_email_verificatioin.xml
> +            <TextView
상품 추가 화면 때도 위 방식처럼 했는데 그 이유가 
뒤로, 확인 버튼은 하단에 고정되어야 하는데 말씀하신 것 처럼 CollapsedToolbarLayout를 적용했을 때 화면 스크롤을 내리지 않으면 하단 버튼이 보이지 않는 이슈가 있어서 toolbar 대신 textVIew로 타이틀을 구성했던 것으로 기억합니다..

만약 CollapsedToolbarLayout를 사용하고자 한다면 회원가입 화면 처럼 버튼이 하단에 고정되는게 아닌 인증번호 레이아웃 아래 위치해야할 것 같습니다. layout margin을 적용하면 아래에 위치할 수는 있겠지만 가로 화면에서 인증번호와 다음 버튼 사이 스크롤 길이가 많이 길어지는 문제가 있습니다. Portrait XML과 Landscape XML을 분리하는 방법도 있긴 한데, 상품 추가 화면에서 CollapsedToolbarLayout대신 textVIew로 타이틀을 구성하는 방법을 이미 사용하고 있기도 하고 CollapsedToolbarLayout을 사용할 만큼 비밀번호 찾기 화면에서는 큰 height를 차지하는 View가 없어서 가로 화면에서도 접을 필요성을 크게 느끼지 못하여 해당 방식을 적용하였습니다.

2024-03-04 07:08 UTC, Taewan-P approved these changes

2024-03-04 07:09 UTC, Taewan-P commented
수고하셨습니다!

2024-03-04 11:49 UTC, EunhoKang approved these changes

2024-03-04 11:50 UTC, EunhoKang reviewed
수고많으셨습니다!

2024-03-04 12:11 UTC, merged