이메일 인증 여부 확인 및 인증 기능 추가
boostcampwm2023/and09-PriceGuard pull request #261
Opened 2024-03-08 07:53 UTC by ootr47

Resolves #<이슈번호>

## 진행 내용

- [x] 이메일 인증 여부 확인 기능 추가
- [x] 미인증 버튼 클릭 시 이메일 인증으로 이동

## 스크린샷 (선택)

<img src="https://github.com/boostcampwm2023/and09-PriceGuard/assets/83055885/a1c0923d-f842-4370-a045-eee7aaf0712a" width="200px;" alt=""/>

2024-03-08 13:15 UTC, EunhoKang requested changes
고생 많으셨습니다!

2024-03-08 13:15 UTC, EunhoKang commented on android/app/src/main/res/layout/fragment_my_page.xml
> +                            app:layout_constraintHorizontal_bias="0.0"
해당 옵션은 지워도 될 것 같습니다.

2024-03-08 13:15 UTC, EunhoKang commented on android/app/src/main/java/app/priceguard/ui/login/findpassword/FindPasswordActivity.kt
> +        Log.d("isFindPassword1", isFindPassword.toString())
테스트 이후 사용되지 않는 로그는 삭제해도 될 것 같습니다.

2024-03-09 13:16 UTC, ootr47 commented on android/app/src/main/res/layout/fragment_my_page.xml
> +                            app:layout_constraintHorizontal_bias="0.0"
해당 옵션이 없으면 이메일이 길어질 시 버튼이 밀려나게 돼서 필요한 옵션인 것 같습니다.
다만 이메일이 잘리는 현상이 있어서 말줄임 표시 속성을 추가했습니다.

2024-03-11 12:51 UTC, EunhoKang commented on android/app/src/main/res/layout/fragment_my_page.xml
> +                            app:layout_constraintHorizontal_bias="0.0"
아 그렇군요 확인했습니다

2024-03-11 12:52 UTC, EunhoKang approved these changes

2024-03-27 06:45 UTC, Taewan-P requested changes
수고 많으셨습니다!!

2024-03-27 06:45 UTC, Taewan-P commented on android/app/src/main/java/app/priceguard/ui/signup/SignupActivity.kt
한 액티비티에 두개의 ViewModel이 있는거에 대해 어떻게 생각하세요? 디자인 패턴을 크게 어기는것 같아서 이렇게 남깁니다.

2024-03-27 06:45 UTC, Taewan-P commented on android/app/src/main/java/app/priceguard/ui/home/HomeViewModel.kt
현재 HomeViewModel에서 이메일 인증 여부를 확인한 후 해당 정보를 저장하는 방식으로 구현되고 있습니다.
Repository 패턴에서는 데이터의 출처와 관계 없이 동일 인터페이스로 데이터에 접속할 수 있게끔 구현하는 방법인데,

TokenRepository에서 인증 여부 요청 -> Repository 내부에서 만약 DataStore에 없다 그러면 API호출 후 값 반환 / DataStore있으면 해당 값 반환 -> 해당 값으로 인증 유무 UI 반영 

이런 방식이 더 깔끔하지 않을까요?

2024-03-29 09:27 UTC, ootr47 commented on android/app/src/main/java/app/priceguard/ui/signup/SignupActivity.kt
MVVM패턴에서 각 뷰에 하나의 뷰모델이 권장되기는 하지만 UI가 복잡하거나, 코드가 중복되는 등 다양한 이유로 코드의 복잡도를 해치지 않는 선에서 여러 개의 뷰모델을 사용하기도 한다고 알고 있습니다. 

회원가입 화면에 있는 이메일 인증 부분을 이미 존재하는 EmailVerificationViewModel을 사용함으로
코드 중복을 줄일 수 있는 이점이 있다고 생각해 2개의 뷰모델을 사용했습니다.

2024-03-29 09:27 UTC, ootr47 commented on android/app/src/main/java/app/priceguard/ui/home/HomeViewModel.kt
아하 인증 여부 정보가 없는 경우에만 api 호출 하는 방법이 깔끔한 것 같네요! 위 방법으로 수정하겠습니다

2024-04-01 07:29 UTC, Taewan-P approved these changes

2024-04-01 07:29 UTC, merged