회원가입 입력 구현
boostcampwm2023/and09-PriceGuard pull request #73
Opened 2023-11-15 13:52 UTC by Taewan-P

Resolves #8, #10, #11

## 진행 내용

- [x] 회원가입 필드 유효성 검사 구현
- [x] 뒤로가기 아이콘 테마에 따라 색상 변경
- [x] 기본 상단바 색상 및 아이콘 색 수정

## 스크린샷 (선택)

<img width="300px" src="https://github.com/boostcampwm2023/and09-PriceGuard/assets/27392567/bd8d6eb1-5f1e-43e9-a16e-13e4fe17a347" />

https://github.com/boostcampwm2023/and09-PriceGuard/assets/27392567/02c58305-c270-4a7d-a346-1f3e4d245aee

2023-11-15 14:40 UTC, ootr47 commented on android/app/src/main/java/app/priceguard/ui/signup/SignupViewModel.kt
> +    data class SignupUIState(
data class 선언 전에 줄바꿈이 필요할 것 같아요

2023-11-15 14:40 UTC, ootr47 commented on android/app/src/main/java/app/priceguard/ui/signup/SignupViewModel.kt
> +    fun updatePassword(password: String) {
혹시 비밀번호와 비밀번호 재입력을 모두 입력한 뒤 비밀번호를 변경했을 때 비밀번호 재입력에서 일치하지 않다는 error를 보여주나요?

2023-11-15 14:40 UTC, ootr47 commented on android/app/src/main/java/app/priceguard/ui/signup/SignupActivity.kt
> +    private fun updateEmailTextFieldUI(state: SignupViewModel.SignupUIState) {
함수를 ActivitySignupBinding의 확장함수로 만드는 것도 방법일 것 같아요

2023-11-15 14:44 UTC, EunhoKang requested changes

2023-11-15 14:44 UTC, EunhoKang commented on android/app/src/main/java/app/priceguard/ui/signup/SignupViewModel.kt
> +    private val passwordPattern = """^[a-zA-Z0-9!@#$%^&*]{8,16}$""".toRegex()
이렇게만 정규식을 짜면 dddddddd 같이 특수문자나 대문자, 숫자가 하나도 포함 안된 것도 통과되지 않나요?

2023-11-16 08:01 UTC, EunhoKang commented on android/app/src/main/java/app/priceguard/ui/signup/SignupActivity.kt
> +        })
```kotlin
private fun getAblBehavior(canDrag: Boolean): AppBarLayout.Behavior {
        val ablBehavior = AppBarLayout.Behavior()
        ablBehavior.setDragCallback(object : DragCallback() {
            override fun canDrag(appBarLayout: AppBarLayout): Boolean {
                return canDrag
            }
        })
        return ablBehavior
    }
```

이런 식으로 줄일 수 있을 것 같습니다.

2023-11-16 08:42 UTC, ootr47 approved these changes
고생하셨습니다!

2023-11-16 08:57 UTC, EunhoKang approved these changes

2023-11-16 08:58 UTC, EunhoKang approved these changes
수고하셨습니다!

2023-11-16 08:59 UTC, merged