로그인 화면 생성, 이메일/비밀번호 유효성 검사, 회원가입 화면으로 전환
boostcampwm2023/and09-PriceGuard pull request #74
Opened 2023-11-15 13:53 UTC by EunhoKang

Resolves #14  
Resolves #15 

## 진행 내용

- [x] 로그인 화면 UI 생성
- [x] 이메일/비밀번호 유효성 검사
- [x] 회원가입 화면 이동

## 스크린샷

<img width="250" alt="스크린샷 2023-11-15 오후 3 52 03" src="https://github.com/boostcampwm2023/and09-PriceGuard/assets/37584805/a21d24e1-425f-439b-962c-de62332a71dc">

2023-11-15 14:25 UTC, Taewan-P requested changes
수고하셨습니다!

2023-11-15 14:25 UTC, Taewan-P commented on android/app/src/main/java/app/priceguard/ui/login/LoginViewModel.kt
> +        val emailPattern = Regex("""^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}${'$'}""")
정규식에서 `$` 표시가 붙여넣기하면서 `${'$'}` 로 escape 처리가 된 듯 합니다.

2023-11-15 14:25 UTC, Taewan-P commented on android/app/src/main/java/app/priceguard/ui/login/LoginViewModel.kt
> +        val passwordPattern = Regex("""(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#${'$'}%^&*]).{8,16}""")
또한 비밀번호 및 이메일 패턴을 회원가입쪽이랑 통일해야 할 것 같습니다.

2023-11-15 14:25 UTC, Taewan-P commented on android/app/src/main/res/layout/activity_login.xml
> +                android:text="@{viewModel.state.email.toString()}" />
state에 값이 있는데 text로 값을 설정해줄 이유가 있을까요?

2023-11-15 14:25 UTC, Taewan-P commented on android/app/src/main/res/values/styles.xml
`@color`를 사용하게 되면 다크모드일때도 light theme의 색상값으로 유지되게 됩니다.

2023-11-15 14:25 UTC, Taewan-P commented on android/app/src/main/java/app/priceguard/ui/login/LoginViewModel.kt
> +    fun logIn(onSuccess: (Unit) -> Unit) {
사소한거긴 한데 로그인은 한단어라 lowerCamelCase 처리가 필요없을 듯 합니다.
```suggestion
    fun login(onSuccess: (Unit) -> Unit) {
```

2023-11-15 14:25 UTC, Taewan-P commented on android/app/src/main/java/app/priceguard/ui/login/LoginActivity.kt
> +        binding = ActivityLoginBinding.inflate(layoutInflater).apply {
[올바른 Scope Function](https://kotlinlang.org/docs/scope-functions.html)을 쓰면 좋을 듯 합니다!

2023-11-15 14:25 UTC, Taewan-P commented on android/app/src/main/java/app/priceguard/ui/login/LoginViewModel.kt
> +        if (emailPattern.matches(_state.value.email) && passwordPattern.matches(_state.value.password)) {
`matches` 보다는 `matchEntire` 함수를 이용해서 문자열과 전체 정규식을 확인하는 방법을 사용하는게 어떨까요?

2023-11-15 14:25 UTC, Taewan-P commented on android/app/src/main/java/app/priceguard/ui/login/LoginViewModel.kt
> +    fun logIn(onSuccess: (Unit) -> Unit) {
그리고 제가 [이 부분](https://github.com/boostcampwm2023/kotlin-p4-onban/pull/70#discussion_r1365309190)에 대해서 리뷰어분께 지적받은 적이 있는데 같이 논의해보면 좋을 것 같습니다.

2023-11-15 15:03 UTC, ootr47 commented on android/app/src/main/java/app/priceguard/ui/login/LoginViewModel.kt
> +    fun logIn(onSuccess: (Unit) -> Unit) {
지금 login 함수가 패턴 검사도 같이 수행하는데 이 부분을 따로 함수로 빼면 어떨까요?

2023-11-15 15:23 UTC, EunhoKang commented on android/app/src/main/java/app/priceguard/ui/login/LoginViewModel.kt
> +        val emailPattern = Regex("""^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}${'$'}""")
수정했습니다!

2023-11-15 15:23 UTC, EunhoKang commented on android/app/src/main/java/app/priceguard/ui/login/LoginViewModel.kt
> +        val passwordPattern = Regex("""(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#${'$'}%^&*]).{8,16}""")
수정했습니다!

2023-11-16 08:44 UTC, ootr47 approved these changes
고생하셨습니다!

2023-11-16 08:45 UTC, Taewan-P approved these changes
수고하셨습니다! 💯

2023-11-16 08:47 UTC, merged