[홈 화면] UI/UX 구현
boostcampwm2023/and09-PriceGuard pull request #95
Opened 2023-11-20 16:49 UTC by EunhoKang

- Resolved #52 
- Resolved #7 

## 진행 내용

- [x] HomeActivity 구현
- [x] 상품 목록 화면, 인기 상품 화면, 마이페이지 구성 후 HomeActivity와 연결
- [x] RecyclerView 구현 후 뷰 연동 

설정 화면은 추후 @ootr47 님과 작업 예정

## 스크린샷 (선택)

https://github.com/boostcampwm2023/and09-PriceGuard/assets/37584805/9bc4482a-1184-4f59-b8e8-70f5646e4ddd

2023-11-21 13:53 UTC, ootr47 requested changes
작성하신 코드가 어마어마 하네요 고생하셨습니다!!

2023-11-21 13:53 UTC, ootr47 commented on android/app/src/main/java/app/priceguard/ui/home/HomeActivity.kt
> +        val navHostFragment = supportFragmentManager.findFragmentById(R.id.nav_host_home) as NavHostFragment
findFragmentById말고 binding으로 접근 할 수 있을 것 같아요!
`val navController = binding.navHostHome.getFragment<NavHostFragment>().navController`

2023-11-21 13:53 UTC, ootr47 commented on android/app/src/main/java/app/priceguard/ui/home/list/ProductListFragment.kt
> +            when (menuItem.itemId) {
현재 itemid 케이스가 R.id.refresh인 밖에 없어서 when문 대신에 if문 사용하면 좋을 것 같아요!

2023-11-21 13:53 UTC, ootr47 commented on android/app/src/main/java/app/priceguard/ui/home/list/ProductListFragment.kt
> +                else -> {
else는 없어도 되지 않을까요?

2023-11-21 13:53 UTC, ootr47 commented on android/app/src/main/java/app/priceguard/ui/home/recommend/RecommendedProductFragment.kt
> +            when (menuItem.itemId) {
이 부분도 같이 수정하면 좋을 것 같아요!

2023-11-21 13:53 UTC, ootr47 commented on android/app/src/main/res/layout/item_product_summary.xml
> +<layout xmlns:android="http://schemas.android.com/apk/res/android"
여기 화면이 디자인과 차이가 있는 것 같아요 ㅜ
텍스트 스타일 지정이랑 카드 뷰 추가 필요할 것 같아요!

2023-11-21 13:53 UTC, ootr47 commented on android/app/src/main/java/app/priceguard/ui/home/ProductSummaryAdapter.kt
> +class ProductSummaryAdapter :
👍

2023-11-21 13:53 UTC, ootr47 commented on android/app/src/main/java/app/priceguard/ui/home/ProductSummaryAdapter.kt
> +                when (item) {
이것도 함수로 빼는 건 어떤가요?

2023-11-21 13:53 UTC, ootr47 commented on android/app/src/main/java/app/priceguard/ui/home/list/ProductListFragment.kt
> +        lifecycleOwner?.repeatOnStarted {
사용하신 것 처럼 viewLifecycleOwner보다 lifecycleOwner쓰신 게 적합한 것 같네요! 👍

2023-11-21 13:53 UTC, ootr47 commented on android/app/src/main/java/app/priceguard/ui/home/ProductSummary.kt
> +        val id: UUID = UUID.randomUUID()
id 사용하신 이유가 diffUtill에서 같은지 판별하려는 용도인 것 같은데
id 없이 hashCode를 사용하면 문제가 있나요?
만약 이 용도가 맞다면 uuid를 선언한게 불필요한 것 같아요

2023-11-21 14:06 UTC, EunhoKang commented on android/app/src/main/java/app/priceguard/ui/home/ProductSummary.kt
> +        val id: UUID = UUID.randomUUID()
맞는 말씀이네요. 전부 삭제하겠습니다.

2023-11-21 14:35 UTC, EunhoKang commented on android/app/src/main/res/layout/item_product_summary.xml
> +<layout xmlns:android="http://schemas.android.com/apk/res/android"
카드뷰 사용해서 전체적인 디자인 일치시켰습니다!

2023-11-21 14:53 UTC, EunhoKang commented on android/app/src/main/res/menu/list_top_app_bar_menu.xml
> +        app:showAsAction="ifRoom" />
아이고 도큐먼트에 있던 걸 베껴쓰다 모르고 저렇게 했네요 수정했습니다

2023-11-21 15:09 UTC, EunhoKang commented on android/app/src/main/res/layout/item_my_page_list.xml
> +            android:id="@+id/tv_product_title"
수정했습니다.

2023-11-21 15:24 UTC, EunhoKang commented on android/app/src/main/res/layout/fragment_product_list.xml
오늘 승준님이 적용하시다가 안하시는거 보고 일단 적용하지 않고 있었습니다. 해당 화면과 인기 상품 화면은 툴바 사라지는 부분 구현할까요?

2023-11-21 15:34 UTC, ootr47 commented on android/app/src/main/java/app/priceguard/ui/home/list/ProductListFragment.kt
> +        lifecycleOwner?.repeatOnStarted {
엇 그러네요 그러면 lifecycleOwner가 아니라 `this@ProductListFragment.repeatOnStarted`가 되어야 할 것 같네요..?

2023-11-21 15:37 UTC, ootr47 commented on android/app/src/main/java/app/priceguard/ui/home/ProductSummaryAdapter.kt
> +                when (item) {
중요한 건 아니고.. 이런 식으로 함수로 뺄 수 있을 것 같아요
```kotlin
fun bind(item: ProductSummary) {
            with(binding) {
                summary = item
                setViewType(item)
            }
        }

        private fun ItemProductSummaryBinding.setViewType(item: ProductSummary) {
            when (item) {
                is ProductSummary.RecommendedProductSummary -> {
                    tvProductRecommendRank.visibility = View.VISIBLE
                    msProduct.visibility = View.GONE
                    setRecommendRank(item)
                }

                is ProductSummary.UserProductSummary -> {
                    tvProductRecommendRank.visibility = View.GONE
                    msProduct.visibility = View.VISIBLE
                    setSwitchListener()
                }
            }
        }
```

2023-11-21 15:48 UTC, Taewan-P requested changes

2023-11-21 15:48 UTC, Taewan-P commented on android/app/src/main/java/app/priceguard/ui/home/HomeActivity.kt
> +        binding = DataBindingUtil.setContentView(this, R.layout.activity_home)
이거 저희 `ActivityHomeBinding.inflate` 로 통일해야 합니다...!

2023-11-21 15:48 UTC, Taewan-P commented on android/app/src/main/java/app/priceguard/ui/home/ProductSummaryAdapter.kt
> +            msProduct.setThumbIconResource(if (msProduct.isChecked) R.drawable.ic_notifications_active else R.drawable.ic_notifications_off)
어짜피 default가 on 이면 off 일때만 resource를 변경해도 되지 않을까요?
```suggestion
            if (!msProduct.isChecked) {
                msProduct.setThumbIconResource(R.drawable.ic_notifications_off)
            }
```

2023-11-21 15:48 UTC, Taewan-P commented on android/app/src/main/java/app/priceguard/ui/home/ProductSummary.kt
인터페이스로 ProductSummary를 상속받는 Data Class를 만들고 싶다면 그 속성을 함수 보다는 그냥 property로 접근할 수 있게끔 만드는게 어떨까요?

```kotlin
package app.priceguard.ui.home

sealed interface ProductSummary {
    val title: String
    val price: String
    val discountPercent: String

    data class UserProductSummary(
        val brandType: String,
        override val title: String,
        override val price: String,
        override val discountPercent: String,
        val isAlarmOn: Boolean
    ) : ProductSummary

    data class RecommendedProductSummary(
        val brandType: String,
        override val title: String,
        override val price: String,
        override val discountPercent: String,
        val recommendRank: Int
    ) : ProductSummary
}
```

2023-11-21 15:48 UTC, Taewan-P commented on android/app/src/main/res/layout/item_my_page_list.xml
>              style="@style/TextAppearance.Material3.BodyLarge"
저는 TextView는 결국 Text이니깐 textAppearance가 더 보기 편하다는 입장입니다.

2023-11-21 15:58 UTC, ootr47 commented on android/app/src/main/res/layout/item_my_page_list.xml
>              style="@style/TextAppearance.Material3.BodyLarge"
아하 좋습니다 TextView에서는 textAppearance속성 활용하는 걸로 수정하겠습니다~!

2023-11-21 16:22 UTC, Taewan-P commented on android/app/src/main/res/layout/fragment_product_list.xml
그럼 내일 추가로 이야기해봐요

2023-11-22 02:19 UTC, EunhoKang commented on android/app/src/main/java/app/priceguard/ui/home/mypage/MyPageFragment.kt
> +
이 부분은 추후에 `//TODO:` 로 남겨두면 좋을 것 같습니다.
이렇게 해두면 나중에 프로젝트에서 추적이 가능합니다.

2023-11-22 06:53 UTC, EunhoKang commented on android/app/src/main/java/app/priceguard/ui/home/mypage/MyPageViewModel.kt
> +    }
위로 올리는게 나아보입니다.

2023-11-22 07:11 UTC, ootr47 approved these changes

2023-11-22 07:12 UTC, Taewan-P approved these changes
수고하셨습니다

2023-11-22 07:28 UTC, ootr47 approved these changes

2023-11-22 07:31 UTC, Taewan-P approved these changes

2023-11-22 07:31 UTC, merged