사용자 인증 및 JWT 갱신 기능 구현
boostcampwm2023/and09-PriceGuard pull request #99
Opened 2023-11-21 13:34 UTC by Muungi

Resolves #98 
## 진행 내용
- [x] JWT 인증을 통한 로그인 사용자 인증 구현
- [x] accessToken 만료시, 갱신 기능 구현
- [x] 발급한 refreshToken을 서버에서 관리하여 보안 수준 강화 

- accessToken이 만료될 경우  클라이언트가 refreshToken을 담아서 재발급 요청을 하는 것을 가정하고,
refreshToken에 대한 유효성 검사를 거친 후 accessToken과 refreshToken을 모두 재발급 합니다.
- refreshToken은 발급 될 때마다 사용자 별로 refreshToken을 서버 db에 저장하여 갱신하고, 이를 refreshToken을 검증하는데 사용합니다.
- 사용자별 최신 refreshToken을 관리하여 refreshToken을 탈취 당하는 경우에 대한 보안을 강화 시킵니다.

## 학습 자료
[nestJS Guards](https://docs.nestjs.com/guards)
[nestJS passport](https://docs.nestjs.com/recipes/passport#implementing-passport-jwt)
[What Are Refresh Tokens and How to Use Them Securely](https://auth0.com/blog/refresh-tokens-what-are-they-and-when-to-use-them/)

2023-11-21 14:13 UTC, sickbirdd requested changes
코드 짜시느라 복잡하셨을텐데 고생 많으셨습니다!!

2023-11-21 14:13 UTC, sickbirdd commented on backend/src/dto/swagger.dto.ts
이 부분은 나중에 Merge할 때 충돌 날 것 같아서 추가하신 부분만 auth.swagger.dto.ts로 따로 저장하는 게 좋을 것 같네요

2023-11-21 14:13 UTC, sickbirdd commented on backend/src/auth/jwt/jwt.guard.ts
> +export class JwtGuard extends AuthGuard('jwt') {}
JwtGuard를 사용하는 곳이 안보이네요. 어디에서 사용하는 건가요?

2023-11-21 15:35 UTC, Muungi commented on backend/src/auth/jwt/jwt.guard.ts
> +export class JwtGuard extends AuthGuard('jwt') {}
Strategy를 커스텀해서 사용하니 필요없을 것 같네요!

2023-11-21 15:36 UTC, Muungi commented on backend/src/auth/auth.module.ts
> +    imports: [TypeOrmModule.forFeature([Token]), forwardRef(() => UsersModule), JwtModule.register({})],
refreshToken을 DB에 저장해서 따로 관리하고 있기 때문입니다

2023-11-22 00:32 UTC, sickbirdd requested changes

2023-11-22 00:32 UTC, sickbirdd commented on backend/src/auth/jwt/jwt.guard.ts
브랜치 버전 충돌 머지하시면서 이전에 리뷰 반영했던 내용들이 다시 되돌아간 것 같아요!
swagger.dto.ts랑 jwt.guard.ts는 지우셔도 될 것 같습니다!

2023-11-22 00:32 UTC, sickbirdd commented on backend/src/exceptions/auth.excetion.ts
그리고 이 파일도 삭제 부탁드립니다!

2023-11-22 01:46 UTC, sickbirdd approved these changes

2023-11-22 01:47 UTC, merged